### ISSUE TITLE
مشکل در بررسی کد احراز هویت client.checkCode

### ISSUE THREAD

**Issue by TrezRayanCo** [erfansahaf/trez-sms-client#1]
سلام
کد احراز هویت ارسال میشه و مشکلی نداره ولی برای بررسی صحت آن در هر صورت 
flase برمیگرده.

**Comment by erfansahaf** [comment]
@TrezRayanCo لطفا کدی که استفاده کردید رو هم قرار بدید.

**Comment by TrezRayanCo** [comment]
client.manualSendCode("09118587876", 595783)
    .then((messageId) => {
        console.log("Sent Message ID: " + messageId);
    })
    .catch(error => console.log(error));

client.checkCode("09118587876", 595783)
    .then((isValid) => {
        if (isValid) {
            console.log("Code 595783 for this number 09301234567 is valid and verified.");
        }
        else {
            console.log("Provided code for that number is not valid!");
        }
    })
    .catch(error => console.log(error));

**Comment by erfansahaf** [comment]
@TrezRayanCo خب شما از متد منوال استفاده کردید. توی این روش سرور شما نمیتونه کد رو چک کنه چون کاربر اون رو ایجاد و ارسال کرده. برنامه نویس باید کد ارسال شده رو توی دیتابیس نگه داره و در اپلیکیشن خودش صحتش رو بررسی کنه.

**Comment by TrezRayanCo** [comment]
client.autoSendCode("09398219817", "Signiture Footer For Branding")
    .then((messageId) => {
        console.log("Sent Message ID: " + messageId);
    })
    .catch(error => console.log(error));


این وب سرویس نیازی به ذخیره کد در دیتابیس از طرف کاربران ما نداره ، بصورت خود کار در دیتابیس های ما ذخیره میشه و با متد زیر چک میشه
client.checkCode("09398219817", "189954")
    .then((isValid) => {
        if (isValid) {
            console.log("Code 595783 for this number 09301234567 is valid and verified.");
        }
        else {
            console.log("Provided code for that number is not valid!");
        }
    })
    .catch(error => console.log(error));

------------
ولی تایید نمیشه

**Comment by erfansahaf** [comment]
@TrezRayanCo توی کد اولتون متد منوال رو صدا زده بودید. اگر متد اتو هم مشکل داره باید بررسی کنم.
تغییری توی ریسپانس وب سرویس ایجاد نکردید؟

**Comment by TrezRayanCo** [comment]
اون منوال همونطور که فرموده بودید بصورت دستی در دیتابیس باید ذخیره بشه ولی اتو به همون شکلی هست که گفتم خدمتتون ، نه تغییری ایجاد نشه و درحال استفاده می باشند

**Comment by erfansahaf** [comment]
@TrezRayanCo دقیقا تایپ ریسپانس تغییر کرده سمت وب سرویس شما. قبلا مقدار 
`CheckSendCodeResult`
از نوع استرینگ بود و الان بولین برگشت داده میشه.

به هر حال نسخه جدید بروزرسانی شد و روی ان پی ام قرار گرفت.

**Comment by TrezRayanCo** [comment]
بله حل شد - ممنون
