### ISSUE TITLE
CORS Error During fetch

### ISSUE THREAD

**Issue by 1mehdifaraji** [erfansahaf/trez-sms-client#3]
با سلام هنگام فچ کردن هر نوع اطلاعاتی از طریق کلاینت با ارور کورس مواجه میشم 

`const TrezSmsClient = require("trez-sms-client");`
`const client = new TrezSmsClient("user...", "mypass...");`

` client
      .accountCredit()
      .then((credit) => {
        console.log(credit + " Rials"); // 500000 Rials
      })
      .catch((error) => {
        console.log(error.isHttpException, error.code, error.message);
      });`

<img width="498" alt="Screen Shot 1400-08-26 at 22 45 03" src="https://user-images.githubusercontent.com/63982703/142267669-b05706b5-4651-4f14-80ff-5ac44e076426.png">

البته در نود جس اس کار میکنه ولی در فرانت ریکت این ارور رو میده

**Comment by erfansahaf** [comment]
This is not related to the package itself. Please reach out to official Trez website support.

Btw, you should not use these kinds of packages on the frontend side.
